#!/usr/bin/env bash
# ----------------------------------------------------------------------------
# AgentStationHub - bash bootstrap for macOS / Linux laptops.
#
# Equivalent of start.ps1 for users who don't have PowerShell installed.
# Covers the happy path: Docker already running, az already logged in,
# .env either present or filled in interactively. For the full-featured
# experience (auto-start Docker Desktop, container-readiness probe, etc.)
# the PowerShell script is the canonical one.
#
# All glyphs are ASCII-only ([OK], [X], [!], *, ===) so the output renders
# correctly on any terminal regardless of locale / code page.
# ----------------------------------------------------------------------------
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

ok()   { printf "  \033[32m[OK]\033[0m %s\n" "$1"; }
info() { printf "  \033[90m*\033[0m    %s\n" "$1"; }
warn() { printf "  \033[33m[!]\033[0m  %s\n" "$1"; }
err()  { printf "  \033[31m[X]\033[0m  %s\n" "$1" >&2; }
hr()   { printf "\n\033[36m=== %s \033[0m%s\n" "$1" "$(printf '=%.0s' $(seq $((74 - ${#1}))))"; }

# --- Prerequisites ----------------------------------------------------------

hr "Environment"
info "OS          : $(uname -s) $(uname -m)"
info "Repo root   : $SCRIPT_DIR"

for f in Dockerfile docker-compose.yml entrypoint.sh .env.example; do
    [[ -f "$f" ]] || { err "Missing required file: $f"; exit 1; }
done
ok "All required files present."

# --- Docker -----------------------------------------------------------------

hr "Docker"
command -v docker >/dev/null || { err "docker CLI not found on PATH"; exit 1; }
ok "docker CLI found: $(command -v docker)"

if ! timeout 8 docker version --format '{{.Server.Version}}' >/dev/null 2>&1; then
    err "Docker daemon unreachable. Start Docker Desktop (or 'sudo systemctl start docker' on Linux) and retry."
    exit 1
fi
ok "Docker daemon reachable: $(docker version --format '{{.Server.Version}}')"

if docker compose version >/dev/null 2>&1; then
    COMPOSE="docker compose"
elif command -v docker-compose >/dev/null; then
    COMPOSE="docker-compose"
else
    err "Neither 'docker compose' plugin nor 'docker-compose' legacy is installed."
    exit 1
fi
ok "Using compose command: $COMPOSE"

# --- Azure CLI --------------------------------------------------------------

hr "Azure CLI"
if ! command -v az >/dev/null; then
    warn "'az' not installed. Sandbox deploys will ask for a device code at runtime."
else
    ok "az CLI found: $(command -v az)"
    if ! az account show --only-show-errors >/dev/null 2>&1; then
        warn "No Azure login detected. Running 'az login'..."
        az login --only-show-errors >/dev/null
        ok "Login completed."
    else
        ok "Already logged in as $(az account show --query user.name -o tsv)"
    fi
fi

# --- .env -------------------------------------------------------------------

hr "Configuration (.env)"
if [[ ! -f .env ]]; then
    warn ".env missing, let's create it."
    read -r -p "  Azure OpenAI endpoint (https://<res>.openai.azure.com/): " endpoint
    [[ -n "$endpoint" ]] || { err "Endpoint is required."; exit 1; }
    read -r -p "  Main deployment (blank = gpt-5.4): " deployment
    deployment="${deployment:-gpt-5.4}"
    read -r -p "  Runner deployment (blank = gpt-5.3-chat): " runnerDeployment
    runnerDeployment="${runnerDeployment:-gpt-5.3-chat}"

    cat > .env <<EOF
# Auto-generated by start.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC").
AZURE_OPENAI_ENDPOINT=$endpoint
AZURE_OPENAI_DEPLOYMENT=$deployment
AZURE_OPENAI_RUNNER_DEPLOYMENT=$runnerDeployment
EOF
    ok ".env created."
else
    ok ".env already exists (not modified)."
fi

# --- Compose up -------------------------------------------------------------

hr "Stack"
info "Building + starting in detached mode..."
$COMPOSE up --build -d
ok "Container started."

# --- Readiness --------------------------------------------------------------

hr "Readiness"
URL="http://localhost:8080/hub"
info "Polling $URL (up to 120 s)..."
for i in $(seq 1 40); do
    if curl -fs --max-time 3 "$URL" -o /dev/null 2>&1; then
        ok "App is up at $URL"
        if   command -v open     >/dev/null; then open "$URL"
        elif command -v xdg-open >/dev/null; then xdg-open "$URL" >/dev/null 2>&1 &
        fi
        cat <<EOF

Next steps:
  *  Tail live log   :  $COMPOSE logs -f agentichub
  *  Stop the stack  :  $COMPOSE stop
  *  Full teardown   :  $COMPOSE down
EOF
        exit 0
    fi
    sleep 3
done

warn "App did not answer within 120 s. Check: $COMPOSE logs --tail 100"
exit 2